---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    template: template.tex
title: "CV - Harvey Barnhard"
fontfamily: libertine
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\section*{Education}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {Harvard University}{Cambridge, MA}
      {Ph.D. in Economics. Fields: Econometrics and Public Finance, Cumulative GPA: 3.77}{2022-}
\resumeSubheading
      {University of Chicago}{Chicago, IL}
      {B.S. in Statistics and B.A. in Economics, Cumulative GPA: 3.78}{2016-2020}
\end{itemize}

\section*{Work Experience}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {Research Assistance}{Cambridge, MA}
      {RA for Professors Isaiah Andrews, Anna Mikusheva, Edward Glaeser}{2022-2025}
\resumeSubheading
      {Teaching}{Cambridge, MA}
      {Teaching Fellow for Ph.D. Math Camp (Econometrics)}{2024-2025}
\resumeSubheading
      {Opportunity Insights (Harvard University)}{Cambridge, MA}
      {Predoctoral Fellow working under Raj Chetty, John Friedman, and Nathaniel Hendren}{2020-2022}
\end{itemize}

\section*{Research}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {True and Pseudo-True Parameters}{2025}
      {\href{https://economics.mit.edu/sites/default/files/2024-04/True\%20and\%20Pseudo-True\%20Parameters.pdf}{{\scriptsize \faLink} Revision requested at Econometric Theory, with Isaiah Andrews and Jacob Carlson}}{}
\resumeSubheading
      {Growing Class Gaps and Shrinking Black-White Race Gaps in Life Expectancy}{2024}
      {\href{https://www.nber.org/conferences/si-2024-workshop-aging}{{\scriptsize \faLink}Working Paper, with Raj Chetty et al.}}{}
\resumeSubheading
      {Approximating Heavy Traffic with Brownian Motion}{2018}
      {\href{http://math.uchicago.edu/~may/REU2018/REUPapers/Barnhard.pdf}{{\scriptsize \faLink} Published by the University of Chicago Mathematics Department (Mathematics REU)}}{}
\end{itemize}


\section*{Research in Progress}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {SURE for Dependent Data and Online Learning}{2025}
      {{Presented in the Econometrics Workshop at Harvard University}}{}
\resumeSubheading
      {Public Provision vs Private Market Subsidies for Affordable Housing}{2025}
      {{With Rob Collinson, Winnie van Dijk, and Daniel Waldinger}}{}
\end{itemize}

\section*{Awards and Affiliations}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {National Science Foundation}{2022-2025}
      {Graduate Research Fellow (\$152,000)}{}
\resumeSubheading
      {Harvard University}{2023-2025}
      {Christopher and Silvana Pascucci Graduate Student Dissertation Fellow}{}
\resumeSubheading
      {U.S. Census Bureau}{2020-}
      {Special Sworn Status}{}
\end{itemize}

\section*{Academic Service}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {Referee}{}
      {American Economic Review (AER)}{}
\end{itemize}
\section*{Skills}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {{\normalfont R, Python, Stata, SAS, Matlab, \CC, SQL, \LaTeX, HTML}}{}
      {}{}
\end{itemize}
\section*{Personal Interests}
\begin{itemize}[leftmargin=0.09in, label={}]
\resumeSubheading
      {{\normalfont Marathon Training (PR: 2:30:11), Photography}}{}
      {}{}
\end{itemize}

